def anaMenu():
  print("\033[1;32;40m   \n")
  print("╔═══════════════════════════════════════════════════╗")
  print("║\033[1;31;40m PYTHON PROJELER \033[1;32;40m        ║")
  print("║                                                   ║")
  print("║ 1-Hesap makinesi                                  ║")
  print("║ 2-Adam Asmaca                                     ║")
  print("║ 3-Not Hesaplama                                   ║")
  print("║ 4-Aritmetik Sayım                                 ║")
  print("║ 5-Çokgen Çizme                                    ║")
  print("║ 6-                                                ║")
  print("║ 7-Aritmetik Sayım                                 ║")
  print("║ 8-Aritmetik Sayım                                 ║")
  print("║ 9-Aritmetik Sayım                                 ║")
  print("║ 10-Çıkış(e)                                       ║")
  print("║ Seçiminiz Nedir                                   ║")
  print("╚═══════════════════════════════════════════════════╝")
  secim = input()
  print("Seçiminiz Nedir?:", secim)
  if secim == "1": hesapMakinesi()
  if secim == "2": adamAsmaca()
  if secim == "3": gectiKaldi()
  if secim == "4": aritmetikSayım() 
  if secim == "5": cokgenCizme() 
  if secim == "10" or secim == "e" or secim == "E":
    print("PROGRAMDAN ÇIKILIYOR")
    exit()    
